name = "OceanGreensFunctionMethods"
uuid = "e3e8a769-591b-4840-946e-301c93ad313e"
authors = ["G Jake Gebbie <ggebbie@whoi.edu>"]
version = "1.0.0-DEV"

[compat]
julia = "1.10"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
